
package agence.gateway.soap.jaxws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ChambreNonDisponibleException", targetNamespace = "http://web.service.hotel/")
public class ChambreNonDisponibleException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ChambreNonDisponibleException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ChambreNonDisponibleException_Exception(String message, ChambreNonDisponibleException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ChambreNonDisponibleException_Exception(String message, ChambreNonDisponibleException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: agence.gateway.soap.ChambreNonDisponibleException
     */
    public ChambreNonDisponibleException getFaultInfo() {
        return faultInfo;
    }

}
