
package agence.gateway.soap.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelService", targetNamespace = "http://web.service.hotel/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toString", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.ToString")
    @ResponseWrapper(localName = "toStringResponse", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.ToStringResponse")
    @Action(input = "http://web.service.hotel/IHotelService/toStringRequest", output = "http://web.service.hotel/IHotelService/toStringResponse")
    public String toString();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeChambreDisponibleToString", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.ListeChambreDisponibleToString")
    @ResponseWrapper(localName = "listeChambreDisponibleToStringResponse", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.ListeChambreDisponibleToStringResponse")
    @Action(input = "http://web.service.hotel/IHotelService/listeChambreDisponibleToStringRequest", output = "http://web.service.hotel/IHotelService/listeChambreDisponibleToStringResponse")
    public String listeChambreDisponibleToString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<agence.gateway.soap.TypeChambre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeTypeChambre", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.ListeTypeChambre")
    @ResponseWrapper(localName = "listeTypeChambreResponse", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.ListeTypeChambreResponse")
    @Action(input = "http://web.service.hotel/IHotelService/listeTypeChambreRequest", output = "http://web.service.hotel/IHotelService/listeTypeChambreResponse")
    public List<TypeChambre> listeTypeChambre();

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "setReservationWM_Auth")
    @RequestWrapper(localName = "setReservationWM_Auth", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.SetReservationWMAuth")
    @ResponseWrapper(localName = "setReservationWM_AuthResponse", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.SetReservationWMAuthResponse")
    @Action(input = "http://web.service.hotel/IHotelService/setReservationWM_AuthRequest", output = "http://web.service.hotel/IHotelService/setReservationWM_AuthResponse")
    public void setReservationWMAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        Personne arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ChambreNonDisponibleException_Exception
     * @throws ReservationFailedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setReservationWM", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.SetReservationWM")
    @ResponseWrapper(localName = "setReservationWMResponse", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.SetReservationWMResponse")
    @Action(input = "http://web.service.hotel/IHotelService/setReservationWMRequest", output = "http://web.service.hotel/IHotelService/setReservationWMResponse", fault = {
        @FaultAction(className = ReservationFailedException_Exception.class, value = "http://web.service.hotel/IHotelService/setReservationWM/Fault/ReservationFailedException"),
        @FaultAction(className = ChambreNonDisponibleException_Exception.class, value = "http://web.service.hotel/IHotelService/setReservationWM/Fault/ChambreNonDisponibleException")
    })
    public void setReservationWM(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws ChambreNonDisponibleException_Exception, ReservationFailedException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficherHotel", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.AfficherHotel")
    @ResponseWrapper(localName = "afficherHotelResponse", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.AfficherHotelResponse")
    @Action(input = "http://web.service.hotel/IHotelService/afficherHotelRequest", output = "http://web.service.hotel/IHotelService/afficherHotelResponse")
    public String afficherHotel();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficherNomHotel", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.AfficherNomHotel")
    @ResponseWrapper(localName = "afficherNomHotelResponse", targetNamespace = "http://web.service.hotel/", className = "agence.gateway.soap.AfficherNomHotelResponse")
    @Action(input = "http://web.service.hotel/IHotelService/afficherNomHotelRequest", output = "http://web.service.hotel/IHotelService/afficherNomHotelResponse")
    public String afficherNomHotel();

}
